In [35]:
import pandas as pd
import os
from settings  import *




pd.set_option('display.max_columns', 200) # So that we can see the full descriptions

In [29]:
variable_descriptions = pd.read_csv(os.path.join(DATA_RAW, 'variable_descriptions.csv'))
data = pd.read_csv(os.path.join(DATA_RAW, 'Train.csv'))

In [11]:
variable_descriptions

,Column,Description,Unnamed: 2,Unnamed: 3
0,dw_00,Percentage of dwellings of type: House or brick/concrete block structure on a separate stand or yard or on a farm,NaN,NaN
1,dw_01,Percentage of dwellings of type: Traditional dwelling/hut/structure made of traditional materials,NaN,NaN
2,dw_02,Percentage of dwellings of type: Flat or apartment in a block of flats,NaN,NaN
3,dw_03,Percentage of dwellings of type: Cluster house in complex,NaN,NaN
4,dw_04,Percentage of dwellings of type: Townhouse (semi-detached house in a complex),NaN,NaN
5,dw_05,Percentage of dwellings of type: Semi-detached house,NaN,NaN
6,dw_06,Percentage of dwellings of type: House/flat/room in backyard,NaN,NaN
7,dw_07,Percentage of dwellings of type: Informal dwelling (shack,in backyard),NaN
8,dw_08,Percentage of dwellings of type: Informal dwelling (shack,not in backyard,e.g. in an informal/squatter settlement or on a farm)
9,dw_09,Percentage of dwellings of type: Room/flatlet on a property or larger dwelling/servants quarters/granny flat,NaN,NaN
10,dw_10,Percentage of dwellings of type: Caravan/tent,NaN,NaN
11,dw_11,Percentage of dwellings of type: Other,NaN,NaN
12,dw_12,Percentage of dwellings of type: Unspecified,NaN,NaN
13,dw_13,Percentage of dwellings of type: Not applicable,NaN,NaN
14,psa_00,Percentage listing present school attendance as: Yes,NaN,NaN
15,psa_01,Percentage listing present school attendance as: No,NaN,NaN
16,psa_02,Percentage listing present school attendance as: Do not know,NaN,NaN
17,psa_03,Percentage listing present school attendance as: Unspecified,NaN,NaN
18,psa_04,Percentage listing present school attendance as: Not applicable,NaN,NaN
19,stv_00,Percentage of households with Satellite TV: Yes,NaN,NaN
20,stv_01,Percentage of households with Satellite TV: No,NaN,NaN
21,car_00,Percentage of households with a car: Yes,NaN,NaN
22,car_01,Percentage of households with a car: No,NaN,NaN
23,lln_00,Percentage listing landline ownership as: Yes,NaN,NaN
24,lln_01,Percentage listing landline ownership as: No,NaN,NaN
25,lan_00,Percentage listing language as: Afrikaans,NaN,NaN
26,lan_01,Percentage listing language as: English,NaN,NaN
27,lan_02,Percentage listing language as: IsiNdebele,NaN,NaN
28,lan_03,Percentage listing language as: IsiXhosa,NaN,NaN
29,lan_04,Percentage listing language as: IsiZulu,NaN,NaN
30,lan_05,Percentage listing language as: Sepedi,NaN,NaN
31,lan_06,Percentage listing language as: Sesotho,NaN,NaN
32,lan_07,Percentage listing language as: Setswana,NaN,NaN
33,lan_08,Percentage listing language as: Sign language,NaN,NaN
34,lan_09,Percentage listing language as: SiSwati,NaN,NaN
35,lan_10,Percentage listing language as: Tshivenda,NaN,NaN
36,lan_11,Percentage listing language as: Xitsonga,NaN,NaN
37,lan_12,Percentage listing language as: Other,NaN,NaN
38,lan_13,Percentage listing language as: Unspecified,NaN,NaN
39,lan_14,Percentage listing language as: Not applicable,NaN,NaN
40,pg_00,Percentage in population group: Black African,NaN,NaN
41,pg_01,Percentage in population group: Coloured,NaN,NaN
42,pg_02,Percentage in population group: Indian or Asian,NaN,NaN
43,pg_03,Percentage in population group: White,NaN,NaN
44,pg_04,Percentage in population group: Other,NaN,NaN
45,lgt_00,Percentage using electricity for lighting,NaN,NaN
46,pw_00,Percentage with piped water access: Piped (tap) water inside dwelling/institution,NaN,NaN
47,pw_01,Percentage with piped water access: Piped (tap) water inside yard,NaN,NaN
48,pw_02,Percentage with piped water access: Piped (tap) water on community stand: distance less than 200m from dwelling/institution,NaN,NaN
49,pw_03,Percentage with piped water access: Piped (tap) water on community stand: distance between 200m and 500m from dwelling/institution,NaN,NaN
50,pw_04,Percentage with piped water access: Piped (tap) water on community stand: distance between 500m and 1000m (1km) from dwelling /institution,NaN,NaN
51,pw_05,Percentage with piped water access: Piped (tap) water on community stand: distance greater than 1000m (1km) from dwelling/institution,NaN,NaN
52,pw_06,Percentage with piped water access: No access to piped (tap) water,NaN,NaN
53,pw_07,Percentage with piped water access: Unspecified,NaN,NaN
54,pw_08,Percentage with piped water access: Not applicable,NaN,NaN
55,ADM4_PCODE,Code for linking row to ward in the wards shapefile,NaN,NaN
56,lat,Lattitude of the center point of the ward,NaN,NaN
57,lon,Longitude of the center point of the ward,NaN,NaN
58,NL,"Nightlights value for the area arounf (lat, lon)",NaN,NaN
59,target,Percentage of women head households with income under R19.6k out of total number of households,NaN,NaN

In [9]:
data

,ward,total_households,total_individuals,target,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,...,pw_03,pw_04,pw_05,pw_06,pw_07,pw_08,ADM4_PCODE,lat,lon,NL
0,41601001: Ward 1,1674.45058,5888.20750,16.773757,0.933841,0.000846,0.005490,0.000676,0.000000,0.001372,...,0.002848,0.007537,0.000000,0.012928,0,0,ZA4161001,-29.682270,24.734743,0.292039
1,41601002: Ward 2,1736.99230,6735.33812,21.496661,0.696940,0.001253,0.004402,0.000000,0.002301,0.001323,...,0.014566,0.057127,0.019092,0.004131,0,0,ZA4161002,-29.119311,24.757737,3.207775
2,41601003: Ward 3,2403.57591,7273.04995,10.931425,0.810545,0.004517,0.008891,0.003986,0.007735,0.000956,...,0.057560,0.010358,0.001421,0.040881,0,0,ZA4161003,-29.142276,25.094093,0.000000
3,41601004: Ward 4,1740.78737,5734.49046,23.119257,0.659914,0.000000,0.006129,0.000000,0.000813,0.037245,...,0.000000,0.000669,0.000000,0.005011,0,0,ZA4161004,-29.372052,24.942867,2.038778
4,41601005: Ward 5,1730.51451,6657.23835,13.652252,0.950575,0.000655,0.001473,0.000598,0.006999,0.000818,...,0.004859,0.001290,0.000673,0.017629,0,0,ZA4161005,-29.409381,25.290165,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2817,34503001: Ward 1,3261.68067,11551.56486,6.393480,0.874972,0.003146,0.017230,0.004735,0.048888,0.000654,...,0.000472,0.000472,0.000000,0.006203,0,0,ZA3453001,-27.675590,23.057920,9.118927
2818,34503002: Ward 2,1463.06432,7908.90411,15.668000,0.636235,0.002262,0.010433,0.000000,0.003030,0.000000,...,0.003030,0.000713,0.000000,0.008414,0,0,ZA3453002,-27.591408,22.907161,1.697395
2819,34503003: Ward 3,1395.18881,6242.37527,13.238795,0.855975,0.006601,0.061118,0.000812,0.003912,0.000812,...,0.002150,0.001458,0.000000,0.003670,0,0,ZA3453003,-27.952550,22.749698,2.792501
2820,34503004: Ward 4,1679.66964,8014.73089,17.639523,0.792552,0.004423,0.016099,0.000000,0.000674,0.000000,...,0.009235,0.007870,0.000000,0.004803,0,0,ZA3453004,-27.913875,22.755314,2.793699
2821,34503005: Ward 5,3008.38687,7899.36498,12.457680,0.254215,0.003310,0.121954,0.000000,0.001770,0.001023,...,0.003107,0.001636,0.000332,0.001770,0,0,ZA3453005,-27.741804,22.856933,0.001200

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2822 entries, 0 to 2821
Data columns (total 63 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ward               2822 non-null   object
 1   total_households   2822 non-null   float64
 2   total_individuals  2822 non-null   float64
 3   target             2822 non-null   float64
 4   dw_00              2822 non-null   float64
 5   dw_01              2822 non-null   float64
 6   dw_02              2822 non-null   float64
 7   dw_03              2822 non-null   float64
 8   dw_04              2822 non-null   float64
 9   dw_05              2822 non-null   float64
 10  dw_06              2822 non-null   float64
 11  dw_07              2822 non-null   float64
 12  dw_08              2822 non-null   float64
 13  dw_09              2822 non-null   float64
 14  dw_10              2822 non-null   float64
 15  dw_11              2822 non-null   float64
 16  dw_12              2822 non-null   int64
 17  dw_13              2822 non-null   int64
 18  psa_00             2822 non-null   float64
 19  psa_01             2822 non-null   float64
 20  psa_02             2822 non-null   float64
 21  psa_03             2822 non-null   float64
 22  psa_04             2822 non-null   float64
 23  stv_00             2822 non-null   float64
 24  stv_01             2822 non-null   float64
 25  car_00             2822 non-null   float64
 26  car_01             2822 non-null   float64
 27  lln_00             2822 non-null   float64
 28  lln_01             2822 non-null   float64
 29  lan_00             2822 non-null   float64
 30  lan_01             2822 non-null   float64
 31  lan_02             2822 non-null   float64
 32  lan_03             2822 non-null   float64
 33  lan_04             2822 non-null   float64
 34  lan_05             2822 non-null   float64
 35  lan_06             2822 non-null   float64
 36  lan_07             2822 non-null   float64
 37  lan_08             2822 non-null   float64
 38  lan_09             2822 non-null   float64
 39  lan_10             2822 non-null   float64
 40  lan_11             2822 non-null   float64
 41  lan_12             2822 non-null   float64
 42  lan_13             2822 non-null   int64
 43  lan_14             2822 non-null   float64
 44  pg_00              2822 non-null   float64
 45  pg_01              2822 non-null   float64
 46  pg_02              2822 non-null   float64
 47  pg_03              2822 non-null   float64
 48  pg_04              2822 non-null   float64
 49  lgt_00             2822 non-null   float64
 50  pw_00              2822 non-null   float64
 51  pw_01              2822 non-null   float64
 52  pw_02              2822 non-null   float64
 53  pw_03              2822 non-null   float64
 54  pw_04              2822 non-null   float64
 55  pw_05              2822 non-null   float64
 56  pw_06              2822 non-null   float64
 57  pw_07              2822 non-null   int64
 58  pw_08              2822 non-null   int64
 59  ADM4_PCODE         2822 non-null   object
 60  lat                2822 non-null   float64
 61  lon                2822 non-null   float64
 62  NL                 2822 non-null   float64
dtypes: float64(56), int64(5), object(2)
memory usage: 1.4+ MB

In [40]:
data.isnull().sum().sum()

0

In [48]:
data['car_00'] + data['car_01'].unique()

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ...
2817    1.0
2818    1.0
2819    1.0
2820    1.0
2821    1.0
Name: car_00, Length: 2822, dtype: float64

In [ ]:
#TODO

from cartopy.crs import LambertConformal, Mercator, Orthographic
import shapely
from cartopy.io.shapereader import Reader
from cartopy.feature import ShapelyFeature
import cartopy.io.shapereader as shpreader


train_data = pd.read_csv(os.path.join(DATA_RAW, 'Train.csv'))
test_data = pd.read_csv(os.path.join(DATA_RAW, 'Test.csv'))



fname = 'data/shapefile/gadm40_ZAF_1.shp'
shapes = list(shpreader.Reader(fname).geometries())



# coordinates of major cities in Africa
cities_data = {
    'city': ['ref', 'Stellenbosch', 'cape_town', 'Durban', 'Johannesburg', 'Soweto', 'Pretoria', 'Port_Elizabeth', 'PieterMaritzburg', 'Benoni', 'Tembisa', 'East_London', 'Vereeniging', 'Bloemfontein'],
    'lon': [30.400, 18.860151, 18.423, 31.029, 28.044, 27.858, 28.188, 25.615, 30.393, 28.321, 28.227, 27.912, 27.926, 26.214],
    'lat': [-24.202, -33.932106, -33.926, -29.858, -26.202, -26.268, -25.745, -33.961, -29.617, -26.188, -25.996, -33.015, -26.673, -29.121]
}


def add_map_features():
    ax.coastlines()
    ax.add_feature(cartopy.feature.BORDERS)
    ax.add_feature(cartopy.feature.OCEAN)
    ax.add_feature(cartopy.feature.LAND)
    ax.add_geometries(shapes,PlateCarree(),edgecolor='black',facecolor='white')


plt.figure(figsize=(24, 16))
central_lon, central_lat = -10, 45
extent = [-40, 20, 30, 60]
ax = plt.axes(projection=PlateCarree())

add_map_features()

ax.scatter(train_data['lon'], train_data['lat'], c=train_data['NL'],
           transform=PlateCarree(),
           s=20,zorder=4
           )

ax.scatter(test_data['lon'], test_data['lat'], color='black',
           transform=PlateCarree(),
           s=20,zorder=4
           )


for i in range(len(prov_list)):
    ax.text(prov_list[i]['lon'], prov_list[i]['lat'],prov_list[i]['province'], transform=PlateCarree(),fontsize=20,zorder=4)
    ax.scatter(prov_list[i]['lon'], prov_list[i]['lat'], color='red', transform=PlateCarree(), s=100,zorder=4)

plt.show()